[package]
name = "fubuki"
version = "0.4.5"
authors = ["xty <xutianyi1999@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
log4rs = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
rand = "0.8"
socket2 = "0.4"
parking_lot = "0.12"
anyhow = "1"
mimalloc = { version = "*", default-features = false }
crossbeam-channel = "0.5"
ahash = "0.7"
futures-util = "0.3"
aes = "0.8"
ctr = "0.9"
md5 = "0.7"
jni = "0.17.0"
android_logger = "0.11"
tun = "0.5"

[profile.release]
lto = true
codegen-units = 1

[lib]
crate-type = ["staticlib", "dylib"]